### ISSUE TITLE
New notebook: Visualize ephys neuronal response to stimulus event (and epochs)

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#104]

**Comment by jeromelecoq** [comment]
@rcpeene will leverage these notebooks for this https://allensdk.readthedocs.io/en/latest/visual_coding_neuropixels.html

**Comment by rcpeene** [comment]
Notebook has been made and a PR has been issued. Looking forward to feedback on it from @jeromelecoq
