### ISSUE TITLE
New notebook: Visualize recorded unit metrics

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#106]
After discussion with Jerome, I've decided to split this task into two notebooks. The first one, `visualize_unit_metrics` is largely copied from [The allensdk](https://allensdk.readthedocs.io/en/latest/_static/examples/nb/ecephys_quality_metrics.html), and takes the user on a tour of the many quality metrics of neuronal units. The second one, `visualize_unit_waveform` will display the spike times and the unit waveforms.

**Comment by rcpeene** [comment]
I've moved `visualize_unit_metrics` to review. At the moment, `visualize_unit_waveform` progress will be tracked by issue #104.

**Comment by rcpeene** [comment]
This is still good for review, but at the moment PR tests are failing due to a DANDI problem.

**Comment by jeromelecoq** [comment]
I was able to run the notebook in binder with a small addition: 
os.environ["DANDI_API_KEY"] = ...

Perhaps you might want to add this as a commented line so that the user knows what to do to get this to work.
