### ISSUE TITLE
Add more thorough explanation of NWB schema in `Reading an NWB File` notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#113]
Jake has requested some sort of NWB schema to better use the data we're giving him. We discussed adding some more explicit and thorough explanations of the major fields of our NWB files in a notebook. It is most appropriate to include this in the second notebook; `Reading an NWB File`.

**Comment by rcpeene** [comment]
Note to consider @Ahad-Allen and @jeromelecoq; How specific to our data will we want this file tour to be? For potential users who are not on the external team, their files might vary from ours, even within ecephys or ophys types. We will have to be careful when we explain the file so that we don't providing misleading information about all files.

**Comment by rcpeene** [comment]
A big table is made [here](https://alleninstitute-my.sharepoint.com/:x:/r/personal/carter_peene_alleninstitute_org/_layouts/15/doc2.aspx?sourcedoc=%7BC25A614B-E93E-4E0D-A2C8-07DAE2A87D61%7D&file=Book.xlsx&action=editnew&mobileredirect=true&wdNewAndOpenCt=1675716067715&ct=1675716068324&wdPreviousSession=e7fdbda6-ac16-47e7-b750-1282ec2d56bf&wdOrigin=OFFICECOM-WEB.START.NEW&cid=300585a3-be5c-444b-a2f1-357807dd9342) of all the major fields of our NWB files. There are many which I am too unfamiliar with to describe. We will need to talk to others to fill this in.

**Comment by rcpeene** [comment]
We have filled in the table. I will export this to a CSV and make a notebook which displays this as a pandas dataframe

**Comment by jeromelecoq** [comment]
Carter to add a number of missing fields to the full list.

**Comment by rcpeene** [comment]
Made the changes to the [Reading an NWB File](https://github.com/AllenInstitute/openscope_databook/blob/dev/docs/basics/read_nwb.ipynb) notebook on `dev` branch.

**Comment by jeromelecoq** [comment]
Can you make the ophys and ephys section more obvious? it is a bit harder to see there are 2 schemas.

**Comment by jeromelecoq** [comment]
otherwise, I would send this to @jsiegle and @westerberg-science for comments

**Comment by rcpeene** [comment]
I think in the static depiction of the notebook its hard to tell, but in Jupyter the tables are obviously delineated. I'll add small headers to separate them more also.

**Comment by rcpeene** [comment]
Headers added.
