### ISSUE TITLE
Allow for selection of peak channel waveform in units table

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#117]
At the moment, each unit within the `units` table in our nwb files has a 2D `waveform_mean` array, where the dimensions are time and channels, and the values are the voltage. Each unit also has a `peak_channel_id` property. These numbers don't seem to reflect the index of the channel within the `waveform_mean` array, as they are very large (like 850264748 in the case of visual coding files).

**Comment by rcpeene** [comment]
According to @Ahad-Allen, these values are a combination of the probe number and the channel index. So probe 2 channel 34 would be encoded as a `peak_channel_id` 234. This makes it impossible to deduce the probe and channel though. 234 could be interpreted as probe 0 - channel 34 _or_ probe 2 - channel 34. We will need to figure out the best way to change the way we encode this. @jeromelecoq might have input, or perhaps we should meet with someone else about this?

**Comment by rcpeene** [comment]
The more I think about it, I don't think the super large values in the visual coding files use this encoding. 850264748 can't represent a probe, because there are certainly not 85 probes, and even if it was probe 8, the remaining value would vastly exceed the number of channels.

**Comment by rcpeene** [comment]
@Ahad-Allen has informed me that the probe number isn't necessarily the 'leading character' but the fourth digit of every `peak_channel_id` so for instance, 234 would necessarily be probe 0. This lines up with his files. However, there is still the mystery of what the `peak_channel_id` means in the visual coding dataset.

**Comment by jeromelecoq** [comment]
Peak channel number is electrode id, which is unique across all sessions. 
@rcpeene to start a microsoft team thread with Josh to discuss. Add a link to it here.

**Comment by rcpeene** [comment]
This was not a bug, simply a slightly unintuitive structuring of data combined with ignorance on my part.
The `peak_channel_id` is the unique electrode channel id across experiments. It can be used as an index in the `nwb.electrodes` table to access the electrode's `local_index`. This `local_index` is the index number of the channel within the probe. This also serves as the index of the peak channel waveform within the `waveform_mean` property of the unit in the `nwb.units` table. Though a little unobvious, we can get the peak waveform of a unit this way.

This has been implemented into my `visualize_unit_responses` notebook easily enough.
