### ISSUE TITLE
Incorporate Colleen's selected figures into Chapter 5

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#124]

**Comment by rcpeene** [comment]
Will be available to assist Colleen. currently awaiting her to begin work on environment.

**Comment by jeromelecoq** [comment]
She said she is planning to work on this in the next  4 weeks

**Comment by jeromelecoq** [comment]
Jerome needs to re-run some conversion for Colleen

**Comment by jeromelecoq** [comment]
There was a bug in dandi causing this issue
this pocked me : 2023-02-01T12:56:25-0800 [WARNING ] dandi 17364:20764 A newer version (0.48.1) of dandi/dandi-cli is available. You are using 0.46.6

Make sure to have the recent version to upload!

**Comment by rcpeene** [comment]
This warning has been there since the beginning of databook. We can make a ticket to update dandi if you'd like.

**Comment by jeromelecoq** [comment]
Colleen said she will work on this next week.

**Comment by rcpeene** [comment]
@colleenjg made a PR #218.
Off the bat I made a few changes, waiting to push them to her repo before merging PR
- Added citation of her paper into the bibliography
- Moved the data files to the data folder
- Added google colab setup cell
- Added utils file to utils package folder

I've requested that she includes some more markdown explaining parts of the notebook before merging.

**Comment by jeromelecoq** [comment]
@rcpeene to ping Colleen

**Comment by jeromelecoq** [comment]
@rcpeene to ping colleen

**Comment by rcpeene** [comment]
PR merged!
