### ISSUE TITLE
Make total spike count histogram

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#131]
After meeting with Ben Hardcastle, we decided we want a figure which shows the total spike count of units over an entire session. Probably make this a histogram. This should go in the neuron epochs notebook.

**Comment by jeromelecoq** [comment]
Total spike count over time

**Comment by rcpeene** [comment]
Pushed with commit d4c896dfa97ad3d60dcb6b531827bff3ef3a2987
