### ISSUE TITLE
Look into getting structure acronyms from channel (identify which notebook to put this in)

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#147]
In `visualize_neuropixel_probes` I added code which identifies brain regions.

**Comment by rcpeene** [comment]
Should the structure acronym be included in the units table? Who do we talk to about this?

**Comment by jeromelecoq** [comment]
Add code to map area units table as part of probe track

**Comment by jeromelecoq** [comment]
Carter is adding code in visualizing visual response to see which area a unit is in..
