### ISSUE TITLE
Ask MPE what running_speed_end_times is

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#156]

**Comment by jeromelecoq** [comment]
Jerome to follow up with MPE

**Comment by Ahad-Allen** [comment]
Carter and I spoke about this yesterday with Arielle and Colin. We were able to determine that end times is generated by looking at the final frame from the sync file. We also discussed potentially having to modify the SDK to account for digitial encoders, though np.0 uses an an analog one and is what most of our experiments were conducted with.

**Comment by Ahad-Allen** [comment]
@rcpeene Added an issue to track this: https://github.com/orgs/AllenInstitute/projects/17/views/1?pane=issue&itemId=20609192

**Comment by rcpeene** [comment]
running_speed_end_times are the ending frame timestamps of each speed tracking timeframe. We have discussed further measures to take on the issue ahad linked above.
