### ISSUE TITLE
Fix display of tables in databook webpage

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#166]
Pandas dataframe outputs don't display properly within the data book like in the following image; 

![Image](https://user-images.githubusercontent.com/23059582/218882172-ded6cd16-4c7c-461b-a2d9-8feebaf3b9df.PNG)

**Comment by rcpeene** [comment]
I've discovered a (slightly inconvenient) solution that will suffice for now here; https://github.com/executablebooks/jupyter-book/issues/1891

**Comment by jeromelecoq** [comment]
This was fixed
