### ISSUE TITLE
Make receptive field notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#169]
This notebook is mostly done I think, on branch `receptive_fields`. Waiting for jerome's feedback.

**Comment by jeromelecoq** [comment]
we talked about adding axis.

**Comment by jeromelecoq** [comment]
We thing adding probe-wise would be useful

**Comment by rcpeene** [comment]
This change has been made.

**Comment by jeromelecoq** [comment]
Looks good. feel free to merge
