### ISSUE TITLE
Discuss how much to rely on pandas?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#170]
The Allen SDK examples use something resembling pandas syntax for accessing all the relevant NWB tables (stim tables, unit table, electrodes table). The PyNWB standard also comes with the to_dataframe() method for tables, not no table operation methods by default, indicating that the intended behavior to parse NWB tables is with pandas. Scientific convention and readability would also dictate we use pandas for this. 

The big problem is that loading these tables (especially the units table) as a pandas dataframe. Takes more than 2 GB of RAM. This doesn't load in binder. In several notebooks now I've run into problems where pandas operations would make the code more conventional, readable, and efficient BUT it wouldn't run on binder, so I've had to refactor the code to work without pandas.

The question is, which way should we go with this? The notebooks are _fine_ without pandas, but there are a few cases where the code requires a bit more explanation to describe how it works and is less conventional. Do we care about this? I don't have strong feelings either way but I wanted to bring this up as its become a relevant issue for my notebooks a few times now. What do @jeromelecoq and @Ahad-Allen think?

**Comment by rcpeene** [comment]
Additional context, one of the biggest inconveniences with not using pandas is in how rows are accessed. The tables are all displayed with the `ID` property for each unit or whatever the table is representing. However if it is not a pandas dataframe it cannot be accessed with the ID, it must be accessed using a regular index. This doesn't sound too hard but it makes it more difficult when transforming tables and storing unique unit indices because the index changes after filtering a table.

**Comment by Ahad-Allen** [comment]
This might become a key issue as we move toward higher-levels of analysis and need to manipulate the arrays for processing more often. Perhaps we can stick to using pandas in notebooks that require enough resources that they wouldn't work with binder anyway? Or would that cause an issue with the consistency of how processing is being presented and done?

**Comment by jeromelecoq** [comment]
Carter to figure out how much memory it needs.

**Comment by jeromelecoq** [comment]
We agree to do most logic outside of pandas
