### ISSUE TITLE
Make Current Source Density notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#178]
I will start by looking into existing code for CSD analysis.

**Comment by rcpeene** [comment]
Updates here https://github.com/NeuralEnsemble/elephant/issues/546#issuecomment-1473626038.
Seems like we have a temp fix for now and they will implement a long term fix.

**Comment by rcpeene** [comment]
There are several options for which way to conduct CSD analysis with elephant. They take x and y coordinates. What we have currently decided to use is to use the channel number to determine relative location along the probe.

**Comment by jeromelecoq** [comment]
Pinging @jsiegle. I just briefly chatted with him
