### ISSUE TITLE
Fix table output in Databook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#179]
As of the latest Databook deployment, when running notebooks in Thebe, cells that output tables display them in a horrendous and unreadable fashion. I don't know why this is happening. Will look into it.

![Image](https://user-images.githubusercontent.com/23059582/224840601-fcab7927-2de7-451a-be3b-344ca3a9936d.PNG)

**Comment by rcpeene** [comment]
My investigation hasn't yielded much insight. I suspect it has to do with new updates to Jupyterbook? I have filed an issue there.

**Comment by rcpeene** [comment]
Issue tracked here https://github.com/executablebooks/jupyter-book/issues/1972

**Comment by jeromelecoq** [comment]
Carter to check latest release

**Comment by rcpeene** [comment]
Looks like this is fixed as far as I can tell in the latest release. Will bump jupyter book version and reploy
