### ISSUE TITLE
where is your code for writing nwb and dandi?

### ISSUE THREAD

**Issue by vickerse1** [AllenInstitute/openscope_databook#197]
Hi,

Have you made this code public? Where is it located?

In particular, for large, combined modality datasets.

Thanks,

Evan

**Comment by rcpeene** [comment]
Thanks for asking!

The code that openscope uses to generate NWB files can be found [here](https://github.com/AllenInstitute/OpenScopeNWB), however, this code is highly tailored to our datasets and internal tools and is all but guaranteed to not work for you. It may be the case that code in there could be repurposed though. This also includes code which uploads to DANDI.

For generating your own NWB files, you might find [Neuroconv](https://neuroconv.readthedocs.io/en/main/index.html) by CatalystNeuro of interest to you.

The NWB specification is highly flexible and data can vary significantly, so at the moment, people will likely have to generate their own files with their own code that leveraged PyNWB. The [PyNWB documentation](https://pynwb.readthedocs.io/en/stable/) can be found here.

Once you have your NWB files, here's info on using DANDI;
https://www.dandiarchive.org/handbook/13_upload/
https://dandi.readthedocs.io/en/stable/modref/dandiapi.html
