### ISSUE TITLE
Add a dev deployment workflow

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#202]
We want a way to deploy a branch to jupyterbook and host it without affecting the production deployment.

**Comment by rcpeene** [comment]
Looks like currently there is no way to deploy a repo to _two_ different github pages sites according to [this]( https://github.com/orgs/community/discussions/47867)

**Comment by jeromelecoq** [comment]
The only way to test deployment is to run locally.

**Comment by jeromelecoq** [comment]
jupyter-book build ./docs
