### ISSUE TITLE
Add citations for technologies and resources

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#208]
There are several places in the databook that mention known and published technologies, DANDI, NWB, Kilosort, Suite2P to name a few. We should add in citations to the relevant literature at these places.

**Comment by rcpeene** [comment]
@katrinaager pointed out that links to documentation/reference material would be good for some notebooks that leverage numpy, matplotlib, interpolation. Later, we will go over with Jerome to add more scientific references.

**Comment by jeromelecoq** [comment]
Done
