### ISSUE TITLE
Make utils to handle shared functionality across notebook. Will need to make the package installed at the start of each notebooks.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#209]

**Comment by rcpeene** [comment]
A couple of action items here;
- Add a `dandi_download` util function in the utils folder which is capable of handling streaming as well
- Edit all notebooks (except the `basic` chapter) to use the download util instead of directly calling dandi code
- In the google colab setup cell of all notebooks, add code which clones the `openscope_databook` repo so our utils code is accessible.

**Comment by rcpeene** [comment]
I've encountered a problem; The utils functionality is added, but importing it is non-trivial. Our notebooks are meant to run on several different platforms. Normally, importing a local python script as a module requires entering the relative path from the script doing the importing, but the different platforms run the notebook from different CWD's relative to the notebook's location. This means that any relative path we include in the notebook might be a valid import on one platform, but invalid on another.

After googling around, apparently in Jupyter, there is no way to get the directory of the notebook being run. (Not to mention in Google Colab, the notebook seemingly doesn't even have a location in the file system). So any solutions that do some examination of the file system and current directory are out.

@jeromelecoq suggests that we make a `setup.py` file which is capable of installing our `utils` files into the Python path, where they will be available for import as long, as the setup has been run. This will be tracked in issue #210

**Comment by rcpeene** [comment]
Okay we've successfully got the setup.py working on colab and binder. Now the download and streaming code in all notebooks should be replaced with usage of `dandi_utils.py`
