### ISSUE TITLE
Binder out of order

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#211]
Launching any branch from our repo on [mybinder.org](mybinder.org) currently fails. After doing some digging, I learned that [Google cloud is no longer supporting binder as of yesterday](https://discourse.jupyter.org/t/mybinder-org-reducing-capacity-unstable/19163) which, according to them, is causing a large amount of problems.

Nothing to do about it at the moment. Hopefully it will be fixed soon.

**Comment by rcpeene** [comment]
Looks like it (tentatively) works now, albeit a bit slow to launch.

**Comment by jeromelecoq** [comment]
Write a FAQ on your website : 
One of these should be about binder.

**Comment by jeromelecoq** [comment]
FAQ in review
