### ISSUE TITLE
Write notebook to do cross-modality alignment (physiological + stim + eye tracking)

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#222]

**Comment by rcpeene** [comment]
PR #233

**Comment by rcpeene** [comment]
Accidentally merged the PR above, but @jeromelecoq can still review the PR of dev #216 and we can change it there.

**Comment by rcpeene** [comment]
Two changes mentioned by Jerome
- Update to use public 2P dandisets. Tracked #245
- "It is showing plots on top of each other that could be achieve without temporal alignement/interpolation. I suggest to show stim triggered averages of all modalities"

**Comment by rcpeene** [comment]
PR #266

**Comment by rcpeene** [comment]
Will try other stimulus times to get a better plot.

**Comment by rcpeene** [comment]
Will zoom in time-wise on epoch plot
