### ISSUE TITLE
Review CEBRA for making a notebook

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#225]
This is https://cebra.ai

**Comment by rcpeene** [comment]
Paste links to scientific papers here.

**Comment by katrinaager** [comment]
https://cebra.ai/docs/usage.html

**Comment by jeromelecoq** [comment]
Katrina needs technical help from Carter on working directory paths

**Comment by jeromelecoq** [comment]
Journal club happened
