### ISSUE TITLE
Finalize the notebook across dandiset to access all relevant metadata and check missing field within dandiset or across dandiset

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#229]
This will be extensive, but I ought to go through all the existing openscope dandisets available and try to run my relevant notebooks on them to identify any critical idiosyncracies.

**Comment by jeromelecoq** [comment]
@rcpeene is making a large metadata notebook across all data in the dandiset. 
Once this is done, @Ahad-Allen and @rcpeene will meet to discuss difference between the dataportal and the excel sheet to see how we can converge to only using the data portal.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add link to sheet

**Comment by Ahad-Allen** [comment]
https://docs.google.com/spreadsheets/d/1TCbagOJEyQDl9-2M6eduYAkRVZ_M2CCSEbUYFSAqpJU/edit#gid=0
