### ISSUE TITLE
Add more low-context description in basics section

### ISSUE THREAD

**Issue by katrinaager** [AllenInstitute/openscope_databook#230]

**Comment by rcpeene** [comment]
I'd say issue titles are best if they are either a question or a brief description of the problem to address (i.e. "some comments are unclear in stream_nwb.ipynb", or "key error in stream_nwb.ipynb). Approving/reviewing modifications to code probably shouldn't be issues themselves, those are more like things that are done _in order to_ resolve an existing issue.
