### ISSUE TITLE
cell_matching.ipynb is not running

### ISSUE THREAD

**Issue by katrinaager** [AllenInstitute/openscope_databook#238]
I cannot run anything in the cell_matching notebook due to multiple ValueErrors and NotFoundErrors for the line: `nwbs = [dandi_download_open(dandiset_id, filepath, download_loc, dandi_api_key=dandi_api_key) for filepath in input_dandi_filepaths]` I am struggling to troubleshoot this and could use some guidance.

**Comment by katrinaager** [comment]
WARNING:root:many=True not supported from argparse
INFO:NwayMatching:NWAY_COMMIT_SHA None
INFO:NwayMatching:Nway matching version 0.6.0
WARNING:root:many=True not supported from argparse
WARNING:root:many=True not supported from argparse
INFO:PairwiseMatching:Matching 1193675753 to 1194754135
INFO:PairwiseMatching:Matching 1193675753 to 1194754135: best registration was ['Crop', 'CLAHE', 'PhaseCorrelate']
[c:\Users\katrina.ager\AppData\Local\Programs\Python\Python39\lib\site-packages\nway\utils.py:48](file:///C:/Users/katrina.ager/AppData/Local/Programs/Python/Python39/lib/site-packages/nway/utils.py:48): FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  df = df.sort_index(0)
[c:\Users\katrina.ager\AppData\Local\Programs\Python\Python39\lib\site-packages\nway\utils.py:49](file:///C:/Users/katrina.ager/AppData/Local/Programs/Python/Python39/lib/site-packages/nway/utils.py:49): FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  df = df.sort_index(1)
INFO:NwayMatching:registration success(1) or failure (0):
   0  1
0  1  1
1  1  1
id map{
  "0": 1193675753,
  "1": 1194754135
}
[c:\Users\katrina.ager\AppData\Local\Programs\Python\Python39\lib\site-packages\nway\nway_matching.py:208](file:///C:/Users/katrina.ager/AppData/Local/Programs/Python/Python39/lib/site-packages/nway/nway_matching.py:208): FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  matching_frame = matching_frame.append(pairframe)
INFO:NwayMatching:Nway matching is done!
INFO:NwayMatching:Creating match summary plots
WARNING:root:setting Dict fields not supported from argparse
[c:\Users\katrina.ager\AppData\Local\Programs\Python\Python39\lib\site-packages\argschema\utils.py:346](file:///C:/Users/katrina.ager/AppData/Local/Programs/Python/Python39/lib/site-packages/argschema/utils.py:346): FutureWarning: '--nway_output.nway_matches' is using old-style command-line syntax with each element as a separate argument. This will not be supported in argschema after 2.0. See http://argschema.readthedocs.io/en/master/user/intro.html#command-line-specification for details.
...
    ssim = structural_similarity(norm_expt_1_avg_img,
  File "c:\Users\katrina.ager\AppData\Local\Programs\Python\Python39\lib\site-packages\skimage\metrics\_structural_similarity.py", line 194, in structural_similarity
    raise ValueError(
ValueError: Since image dtype is floating point, you must specify the data_range parameter. Please read the documentation carefully (including the note). It is recommended that you always specify the data_range anyway.
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?78bdcbda-b497-4759-be75-4ae4b6a1fbe0) or open in a [text editor](command:workbench.action.openLargeOutput?78bdcbda-b497-4759-be75-4ae4b6a1fbe0). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by rcpeene** [comment]
Hint you can surround blocks of code/error text with ` ``` ` on either side and it will display a bit more neatly

**Comment by rcpeene** [comment]
Fixed the problem. It was a dependency issue. Just needed to reinstall our requirements.
