### ISSUE TITLE
Make Intro Intro notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#242]
@katrinaager to make a notebook that accomplishes two things
1. gives a conceptual introduction to the ecosystem
2. provides reference material/resources and serve as an index of sorts.

**Comment by rcpeene** [comment]
Links to include
https://nwb-schema.readthedocs.io/en/latest/
nwbwidgets discussion


- paragraph on NWB files (why they exist, what they do)
- paragraph on DANDI (why it exists, what it does, why/how we use it)
- explanation of finding dandisets, filepaths

**Comment by jeromelecoq** [comment]
Add a link to the notebook

**Comment by katrinaager** [comment]
https://github.com/AllenInstitute/openscope_databook/blob/dev/docs/basics/intro_information.ipynb

**Comment by jeromelecoq** [comment]
This should be the start of a method section. @rcpeene to make a method chapter with the content you want to cover in there and @katrinaager can add one or more of those notebook.

**Comment by katrinaager** [comment]
I think this issue can be closed since the intro notebook is the same thing as the methods section I just made.
