### ISSUE TITLE
dandi download open not showing loading bar?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#254]
Dandi download open used to show download bar but not is not. Will look into why.

**Comment by jeromelecoq** [comment]
We have an issue on Dandi api repo. @rcpeene to link it here

**Comment by rcpeene** [comment]
https://github.com/dandi/dandi-cli/issues/1159

**Comment by jeromelecoq** [comment]
Jerome is going to talk in Boston with them
