### ISSUE TITLE
Apply CEBRA Time to meaningful

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#260]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8856714/

**Comment by jeromelecoq** [comment]
The dandiset is here : https://dandiarchive.org/dandiset/000036?page=2&sortOption=0&sortDir=-1&showDrafts=true&showEmpty=false&pos=14

**Comment by jeromelecoq** [comment]
We just need to sort the columns.

**Comment by jeromelecoq** [comment]
Next step is to get Mathis lab review

**Comment by rcpeene** [comment]
Merged to main
