### ISSUE TITLE
Make raster spike matrix notebook with Pamela

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#264]
The goal of this to help Pamela do analysis of her datasets but also consolidate a notebook that helps create a 3d array (neuron, time and trials) that could be used to export a data matrix. 
This could be used to export datasets out of NWB files and facility analysis in Matlab for example

**Comment by rcpeene** [comment]
PR #273

**Comment by jeromelecoq** [comment]
This is good. Just for one typo re-reading
