### ISSUE TITLE
Review Classifying Waveforms Notebooks to be pushed to dev

### ISSUE THREAD

**Issue by katrinaager** [AllenInstitute/openscope_databook#282]
Carter has already reviewed this notebook, but now that changed have been made, it could use another review. Jerome, could you please look over it as well whenever you have a chance so it can be pushed to dev.  PR: https://github.com/AllenInstitute/openscope_databook/pull/281

**Comment by jeromelecoq** [comment]
Let's push the part without opto-tagging for now

**Comment by jeromelecoq** [comment]
We can close, this was reviewer before
