### ISSUE TITLE
Get Google Analytics?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#283]
After looking into it, it seems that it would be very easy to get Google Analytics or Plausible Analytics integrated into the databook. Just need to make an account and add a parameter to the databook config.

**Comment by rcpeene** [comment]
Should be done. Waiting to deploy to see..

**Comment by rcpeene** [comment]
Done and deployed!

**Comment by jeromelecoq** [comment]
Working, to move under the openscope gmail
