### ISSUE TITLE
Handle `out of space` error for tests

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#287]
After adding cebra dependency, the tests all fail before they really start and yield `no space left on device`; the Github Ubuntu runner can't contain all the dependencies that we have (cebra is large). We need to find a way to get more space.

**Comment by rcpeene** [comment]
Some options:
- There's a github action which deletes a bunch of linux files in the default ubuntu runner. This can supposedly double our space
- We can get a 'larger runner' with Github. (I think for no cost). We will need to discuss this with whoever is in charge of the Allen Institute Github organization
- We could do a self-hosted runner. We would need a dedicated machine that we can keep running 24/7. This might require some environment setup.

**Comment by jeromelecoq** [comment]
@fcollman up our test unit. We need to confirm this fixes our issues.

**Comment by jeromelecoq** [comment]
We have issues with simultaneous access to NWB files which are not allowed by h5py. Solution is to force renaming of raw files when running in tests to paralleled access. Potentially use a random string with a env variable boolean set by a GitHub action.

**Comment by fcollman** [comment]
https://docs.h5py.org/en/stable/mpi.html

this suggests that parallel read is allowed

**Comment by jeromelecoq** [comment]
Enforcing that all notebook work with a. different session fixes the access issue. 
We will continue this way for now.
