### ISSUE TITLE
Create a tca notebook

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#288]
There is a python library associated with this paper : 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6907734/pdf/nihms-976117.pdf

https://github.com/neurostatslab/tensortools

**Comment by rcpeene** [comment]
Got TCA to run, but the components don't look great. Current task; subselect the data to find better results

**Comment by jeromelecoq** [comment]
Jerome to ask in Boston at Alex in person

**Comment by jeromelecoq** [comment]
From Alex: 
Hi Jerome,

It looks great! More interpretation of the factors you get out would be useful.

I think the reason you need a lot of components is that the natural movie stimulus evokes very rich / high-dimensional temporal dynamics. Potentially it might lead to more interpretable factors if you look at static natural images with shorter trial duration. And then you could also mix in several different image types, which different trial factors would pick up.

A long time ago (probably 7 years ago, before we even published the paper) I ran TCA on some Allen data and found that some of the trial factors correlated with the animal's running speed. It would be good to check for something like this.

Also, this is a nice method to try out if you haven't seen it already: [https://www.biorxiv.org/content/10.1101/2023.03.01.530616v1](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2F10.1101%2F2023.03.01.530616v1&data=05%7C01%7C%7Cbe3134d2b7244891a14d08dbccbeead8%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C638328892619220775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ao3CGO454mf2SJAoOmEmns7vIOUAvkNSfDKiEnonjnA%3D&reserved=0)

-- Alex
