### ISSUE TITLE
Add Github workflow for testing environment

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#29]
We need to incorporate the installation of the dependencies to a workflow. We could make it separate from the build workflow, but might be best to add it to build workflow. Will become clearer after #17.

**Comment by rcpeene** [comment]
I've added a basic check within our Github CI workflow in this commit. 89d8a11. All it does is try to pip install from requirements.txt. Perhaps a more robust system could be developed in the future.

**Comment by jeromelecoq** [comment]
That seems like a good start
