### ISSUE TITLE
make opto-tagging notebook show clearly all laser protocols and show clearly positive and negative types.

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#291]

**Comment by jeromelecoq** [comment]
@rcpeene to add plots and code here for 3 conditions. We currently do not see consistent cells picked across all laser protocols. We want to rule out chance occurrence.

**Comment by rcpeene** [comment]
three sorted plots for visual coding `sub-730760263/sub-730760263_ses-755434585.nwb`

![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/ec23bf7b-bc53-4a52-88b4-b5cff0a771b7)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/d91f5355-4e35-41af-aa20-b4f6e337091d)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/1392db0f-e186-4bb3-8a39-9d588c1af2af)

**Comment by rcpeene** [comment]
Plots for a pvalb mouse `sub-730760263/sub-730760263_ses-755434585.nwb`



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/89781632-6658-4eee-8882-68c3b4dc9188)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/3cb955d1-8aec-429d-8b83-4cbe6d2c6fee)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/93cef72d-74ae-43d5-b7f3-97e6da3a1443)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/b6069fd9-382b-4f33-af93-dd8f0b1fefcc)

**Comment by rcpeene** [comment]
SST mouse `sub-735109599/sub-735109599_ses-758798717.nwb`


![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/d5be4143-f1f0-4925-9707-5eff1c6e7688)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/8020400a-e758-4c0b-9480-2cae3c03c96b)



![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/b74c80e1-6c0a-4467-a4c7-d9e9790b8bff)

**Comment by rcpeene** [comment]
wildtype mouse


![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/89c7ebd9-90ba-473e-98fe-b28e3276c480)

**Comment by jeromelecoq** [comment]
https://github.com/AllenInstitute/optotagging/blob/main/optotagging_results.py 
Jerome to try this code a little more

**Comment by jeromelecoq** [comment]
There were issues with cells that show as not opto-tagged throughout many experiment causing us to be confused with responses. We confirmed that an LED was used for most of this dandiset with no direct response in cells. 
In later session, a laser was used with stronger impact. 

We agreed to move to dandiset 22 to fix this issue

**Comment by jeromelecoq** [comment]
Merged
