### ISSUE TITLE
use latest html repr for neurodata objects

### ISSUE THREAD

**Issue by bendichter** [AllenInstitute/openscope_databook#299]
<img width="823" alt="image" src="https://github.com/AllenInstitute/openscope_databook/assets/844306/78da1f4f-7181-4e40-894c-73707c50b72e">

I noticed a few places like this in the notebooks where you are printing neurodata objects. This is totally fine to so, but I wanted to make you aware of a new feature that you might prefer. With the latest version of PyNWB, now you can repr an object (the last line would change from `print(eye_tracking)` to simply `eye_tracking`) and it will output an interactive tree that represents the entire neurodata object, e.g.

<img width="731" alt="image" src="https://github.com/AllenInstitute/openscope_databook/assets/844306/ad1ae2be-be83-4e8e-80bc-39c9fe4ef0f3">

**Comment by rcpeene** [comment]
Ah, thanks for letting us know! I just happened to notice this on Friday as well. Will make these changes.
