### ISSUE TITLE
Make GLM Notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#311]

**Comment by jeromelecoq** [comment]
Carter to copy plot to this issue. 
Add link to GitHub Branch.

**Comment by rcpeene** [comment]
Tested how a very simple GLM performs as the length of some synthesized flash stimulus and synthesized spike responses increases.


![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/ad745163-14e5-44b3-8d51-737167cfa02c)


![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/c69a7ceb-cfee-405f-bb87-e81bac97c2ac)

**Comment by jeromelecoq** [comment]
Link branch here.

**Comment by rcpeene** [comment]
https://github.com/AllenInstitute/openscope_databook/tree/glm
two files with related code

**Comment by rcpeene** [comment]
Reviewed and merged
