### ISSUE TITLE
One exp in barcoding has uneven wheel sampling of running speed

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#324]
![Image](https://github.com/AllenInstitute/openscope_databook/assets/2491343/a49d4fea-5ea6-4168-91e0-ef47fb4db488)

**Comment by jeromelecoq** [comment]
Duplicate of another issue

**Comment by rcpeene** [comment]
duplicate of https://github.com/AllenInstitute/OpenScopeNWB/issues/178
