### ISSUE TITLE
In Exploring an NWB File, consider using html_repr

### ISSUE THREAD

**Issue by bendichter** [AllenInstitute/openscope_databook#329]
The html repr function has improved greatly since the "Exploring an NWB File" notebook was created. Could you add it here? It could potentially replace the print.

To view the html_repr in a notebook, you just need the last line to return the value of the thing you are inspecting, e.g.

instead of

```python
io = NWBHDF5IO(filepath, mode="r", load_namespaces=True)
nwb = io.read()

print(nwb)
```

you could simply write

```python
io = NWBHDF5IO(filepath, mode="r", load_namespaces=True)
nwb = io.read()

nwb
```

This provides an interactive collapsable view of the file.

**Comment by rcpeene** [comment]
Implemented
https://github.com/AllenInstitute/openscope_databook/commit/90519fabe98477cebd765dc20f8ee1407167e0ab
