### ISSUE TITLE
Stim epochs overlap in GLO files

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#331]
After plotting the stim epochs of a GLO file, it looks like there is a significant overlap between receptive field epoch and gratings. I verified these numbers from the tables in the file. What could cause this?

sub-1170220944/sub-1170220944.nwb
![Image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/8103dd49-789e-4504-bed8-e6d23bc8c543)

**Comment by rcpeene** [comment]
Confirmed also occurs in sub-1169714184/sub-1169714184.nwb
![image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/0f317c76-0f14-4875-8588-ae082edd669d)

**Comment by jeromelecoq** [comment]
This needs to be looked at by the team.

**Comment by jeromelecoq** [comment]
@rcpeene to ping them

**Comment by Ahad-Allen** [comment]
This is part of the script that was shown, not a packaging issue.

**Comment by jeromelecoq** [comment]
Unfixable
