### ISSUE TITLE
Fix erroneous test workflows?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#337]
Had some strange behavior with a [build workflow failing](https://github.com/AllenInstitute/openscope_databook/actions/runs/7619166421) on a file even though the [prior test succeeded](https://github.com/AllenInstitute/openscope_databook/actions/runs/7619166166). The line that was the reported cause of the error seemed to be using a different version of the file that was not the latest.

It is probably because the build test is setup improperly. Must investigate.

**Comment by rcpeene** [comment]
I think I was misled; the tests run fun as they are. I must have mistakenly pushed a commit to main that did not pass tests, which then made all subsequent `build` runs on main. In other words, if main is put into a position where it fails tests, then all PR build tests into main will fail.

**Comment by jeromelecoq** [comment]
This worked recently. Let's close unless it reappears
