### ISSUE TITLE
"403: Forbidden" error whenever I try to launch JupyterHub from any OpenScope page

### ISSUE THREAD

**Issue by NilsNyberg** [AllenInstitute/openscope_databook#339]
As the title says. It happens with every page I have tried on https://alleninstitute.github.io/openscope_databook. The error is described here: https://jupyterhub.readthedocs.io/en/stable/faq/troubleshooting.html

**Comment by rcpeene** [comment]
Does the same error occur when you go directly to [hub.dandiarchive.org](hub.dandiarchive.org)?

**Comment by NilsNyberg** [comment]
Yes same problem. Have tried with different computers, but not different GitHub accounts. Is it something with my account?

**Comment by rcpeene** [comment]
This means that it is not an issue with the databook but rather your machine's connection to dandihub. 403 forbidden errors are client-side errors. Perhaps related to your network or your web browser. Here are some potential fixes for 403 errors.

https://www.hostinger.com/tutorials/what-is-403-forbidden-error-and-how-to-fix-it

**Comment by NilsNyberg** [comment]
So I have now tried different computers and different github logins at different IP adressess throughout London (UK), and I always get the same message. What could this mean? That hub.dandiarchive.org can't be reached from the UK for whatever reason?

**Comment by rcpeene** [comment]
The devs of Dandihub might be able to answer that. I'd recommend filing an issue there
https://github.com/dandi/dandi-hub
