### ISSUE TITLE
Add pynapple notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#342]
- Take time to explore Pynapple and identify potentially useful methods
- Write code to use illusion to use correlogram

**Comment by jeromelecoq** [comment]
Can @rcpeene share notebook here

**Comment by rcpeene** [comment]
https://github.com/AllenInstitute/openscope_databook/blob/pynapple/docs/first-order/correlograms.ipynb

**Comment by rcpeene** [comment]
PR here 
https://github.com/AllenInstitute/openscope_databook/pull/369
