### ISSUE TITLE
Confirm there aren't units outside the surface of the brain in our NWB files

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#345]
Dan Birman gave a presentation and showed that in the data he used, there were Units outside the surface of the brain.
I inquired about this and he said he used
https://allensdk.readthedocs.io/en/latest/_static/examples/nb/visual_behavior_neuropixels_data_access.html
this code.

I should check this in our files.

**Comment by jsiegle** [comment]
I think there are some rare cases where units inside the brain will be assigned to root (for example if they fall in a voxel without any CCF label). But this should happen infrequently enough that it's fine to exclude any units with this label.
