### ISSUE TITLE
Review: suggestions for overview and "Basics" section

### ISSUE THREAD

**Issue by stephprince** [AllenInstitute/openscope_databook#374]
The introduction and basics section are really nice and easy to follow! After reviewing, I added some suggestions here. I also have a few very small text suggestions for some of the markdown parts, but it might be easier if I suggest them in a PR. Let me know if you think there is a better way to structure the review going forward with the other sections.

### OpenScope Databook
- **Dandihub:** I ran into the same issue as #346 when trying to run in a dandihub notebook. 
- **Locally:** "It is recommended that this is done within a conda environment using Python 3.8" I think it would be helpful to give explicit command line instructions for setting up a new conda environment, especially to make sure users are installing the correct version of python. I had some dependency resolution issues with python 3.8 but 3.9 worked ok.
- I think it might be helpful if the **How can I use it?** section was more easily accessible (maybe it's own notebook / section on the left side bar)? When I was getting set up it was not immediately obvious where to find installation instructions.

### Basics - Background
- There were some broken links: _Explore an NWB File_, _Visualizing Raw 2-Photon Images_, _Visualizing LFP responses to Stimulus_.

### Basics - Reading an NWB File
- **Reading an NWB File** - I saw that an older version of `pynwb` was pinned to the requirements. You are probably aware but I just wanted to suggest that more recent versions have some nice html representations of NWB files inside Jupyter notebooks that are great for exploring the file and might be preferable over `print(nwb)` statements. 
- **OpenScope's File Schemas** - I think it would be helpful to very briefly explain what a schema is / what it is used for in this markdown section.

### Basics - Streaming an NWB File with fsspec
- The section starts off mentioning streaming with `fsspec`, but then uses `remfile` instead. I suggest replacing references to `fsspec` with more general descriptions of streaming.
- This might be a personal preference, but I felt like the sections might flow more logically if _Downloading an NWB File_ was followed by _Streaming an NWB File_ to provide two different options for accessing data.

### Basics - Getting Experimental Metadata from DANDI
- **Get NWB Info**: In this section and the **Getting Table** section, the commented out lines were a little hard to read. A flag for ophys vs. ecephys datasets might be more readable instead of commented/uncommented blocks.
- **Getting Table**: the ophys summary code errored, I think because `sub_name` was not saved as a variable in the `get_nwb_info` and "convert table to pandas dataframe" ophys sections.
- **Selecting Files**: The commented out `sub_sex` and `#_units` dataframe filtering needs underscores to run successfully.

**Comment by rcpeene** [comment]
Thanks! I have given you write permissions to the repo so if you have small changes to make you can do so. I'd advise using the `scientific_review` branch for such commits.

**Comment by rcpeene** [comment]
`I wanted nted to suggest that more recent versions have some nice html representations of NWB files inside Jupyter notebook`
Yes, we jumped at the chance to implement this but it turns out it would cause these crazy halting errors during our test runs. I believe the issue was reported; maybe worth checking its been patched.

**Comment by rcpeene** [comment]
All feedback addressed in PR #375 . The error with building wheels on Dandihub is being investigated.

**Comment by stephprince** [comment]
Changes in the PR look good! I've pushed my edits to the branch as well.

> Yes, we jumped at the chance to implement this but it turns out it would cause these crazy halting errors during our test runs. I believe the issue was reported; maybe worth checking its been patched.

There was a recent patch for recursion errors in some datasets, I'm not sure if that was the same issue or not. If you can point me to the relevant pynwb issue I can also try to take a look.

**Comment by rcpeene** [comment]
Looking for permission to close this issue @stephprince

**Comment by stephprince** [comment]
all good with me!
