### ISSUE TITLE
Bug: Import missing in cred_assign_figures.ipynb 

### ISSUE THREAD

**Issue by colleenjg** [AllenInstitute/openscope_databook#380]
In the following try, except statement, I forgot to reimport `cred_assign_utils` at the end of the except clause. As a result, the notebook fails if the code goes through the except clause.
```
import os
try:
    from databook_utils import cred_assign_utils
except:
    !git clone https://github.com/AllenInstitute/openscope_databook.git
    %cd openscope_databook
    %pip install -e .
```
Will fix in a moment.

**Comment by rcpeene** [comment]
Merged into dev
