### ISSUE TITLE
Alter Jupyter configuration parameters on Binder

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#40]
Databook can now be launched via binder. However, there is an error on visualize_neuropixel_probes which causes an error; `IOPub message rate exceeded.` which exits the kernel. This can be fixed by changing the Jupyter config. However, on binder we don't have direct access to the instantiation of Jupyter. Am looking into ways to do this.

**Comment by rcpeene** [comment]
I've found potential solutions in using a postBuild script https://github.com/jupyterhub/binderhub/issues/375. This doesn't seem very robust, but may suffice. I am not looking into the documentation to find the best way to handle jupyter_config settings.

**Comment by jeromelecoq** [comment]
@rcpeene can now achieve this ticket, ie alter jupyterhub settings. 
But still have issues with another issue #42
