### ISSUE TITLE
Binder kernel crashes with brainrender script

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#42]
When attempting to download a brian atlas in binder, the kernel crashes. The resulting error is something like "ioPub rate exceeded"

**Comment by rcpeene** [comment]
Further discussion in #40

**Comment by jeromelecoq** [comment]
@rcpeene is trying to figure out the limits of binder and a potential conflict with brainrender.

**Comment by rcpeene** [comment]
The kernel crashing does not appear to be a result of an "out of memory" error. The last memory reading in the toolbar before the crash was about 500 / 2000 MB.

**Comment by rcpeene** [comment]
In the brain atlas download code, there doesn't appear to be anything special that might crash the kernel. It just downloads the file in chunks over http, and then decompresses the file afterward. Perhaps the decompression could be too expensive?

**Comment by jeromelecoq** [comment]
Carter will file an issue on binder repo with replicable code.

**Comment by jeromelecoq** [comment]
some actions happened on the submitted issues but not details.

**Comment by jeromelecoq** [comment]
Given no actions on external tickets, we discussed a work around whereby we would manually download the dependency in the notebook prior to brain render to isolate the issue.

**Comment by rcpeene** [comment]
After digging around the file system and identifying where the brain atlas exist, I found that downloading it works! Yet the kernel still crashes when trying to instantiate the scene. I had erroneously thought the crash was during the file download because the brainglobe download bar is dysfunctional. It seems the _real_ problem is in generating a pop up window.

**Comment by rcpeene** [comment]
It might be the case the using an embedded window rather than a popup will fix it. Brainrender has a bug with embedded windows in Jupyter, discussed [here](https://github.com/brainglobe/brainrender/issues/219). Will downgrade rich to see if this works.

**Comment by rcpeene** [comment]
I have issued a [PR with brainrender](https://github.com/brainglobe/brainrender/pull/223) to fix this bug. Hopefully this will be a sufficient workaround for our crashing problem.

**Comment by rcpeene** [comment]
Brainrender was expedient and released merged my PR and released a new version today, fixing this bug! The bad news is there are additional obstacles. There are 3 ways to render a brainrender scene in a notebook. They all seem to fail for different reasons. One of them (popup window), which is what we have been using, works on my machine but fails on binder. The other two involve an embedded window. I feel as though this should work embedded but doesn't for unknown reasons. Will fill an issue on brainrender.

**Comment by jeromelecoq** [comment]
@rcpeene will work toward using a brain rendering package in pynwb since brain render is causing replication issues.
