### ISSUE TITLE
Figure out best way to manage files with Thebe in Jupyter Book

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#51]
When running notebooks with Thebe in Jupyter Book, a line that downloads to "../../data/myfile.nwb" causes an "directory doesnt exist" error. Will investigate how file structure works with a Thebe kernel so we can write notebooks accordingly.

**Comment by rcpeene** [comment]
The default directory '~' is the main repo directory. !cd commands do not work, but file paths work normally as long as they use ~ as the explicit or implicit point of reference. This is different from how the files work on binder. We will have to discuss best practices in notebooks here in terms of clarity and flexibility.

**Comment by rcpeene** [comment]
Using ~/ as the form for all file locations should suffice.

**Comment by jeromelecoq** [comment]
We agreed!
