### ISSUE TITLE
Make 2p raw data access notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#54]
I should make a notebook that describes how to use ZSTD compression, mentioned [here](https://github.com/AllenInstitute/OpenScopeNWB/issues/43)

**Comment by rcpeene** [comment]
The best way to visualize the 3d raw 2p data will probably require mpl_interactions library. Issue #60 will include this.

**Comment by rcpeene** [comment]
It seems as though users won't need to handle decompression, and neither do I! As far as I can tell, decompression is handled by PyNWB automatically when the file is read.

**Comment by jeromelecoq** [comment]
Example view in this paper : https://www.nature.com/articles/nn.3867

**Comment by jeromelecoq** [comment]
@jeromelecoq and @rcpeene will review NWB regions data together

**Comment by jeromelecoq** [comment]
We discussed. @rcpeene was starting to put together a comprehensive real time view of the movies along with traces. This might be a separate effort. We will focus on static representations for now for this notebook.

**Comment by jeromelecoq** [comment]
We need to make sure the notebook showcase the time of each frame in the raw data. @Ahad-Allen will provide how to find this info.

**Comment by Ahad-Allen** [comment]
I believe this information is stored here in the NWB:


![Image](https://user-images.githubusercontent.com/87045911/201752823-8a8bfb3c-0acc-4a03-8dd5-2654586b70c3.png)

You should be able to map the frametimes from the raw to these to get the exact timings.

**Comment by rcpeene** [comment]
A basic version of this notebook has been pushed to its own branch `visualize_2p_raw`. Will issue a PR into dev when the current PR from dev to main is closed.

**Comment by jeromelecoq** [comment]
@rcpeene to link PR here

**Comment by jeromelecoq** [comment]
Ok, first the branch run on Binder. This is great!

**Comment by jeromelecoq** [comment]
I had to give api key and link to a private dandiest which is not ideal. I just asked Ben if there are public raw data available on dandi.
