### ISSUE TITLE
Add download cells to the top of notebooks

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#63]
@jeromelecoq And I discussed that the notebooks could benefit from having relevant example files included within each notebook. Different public data can be used for different notebooks as needed. I will have to go through the existing notebooks and add this.

**Comment by rcpeene** [comment]
To do this, I will need good example files to use for each notebook.

**Comment by rcpeene** [comment]
We've learned that visual coding may not be ideal for finding example nwb files for neuropixel probe visualization due to an error with the CCF coordinates. (#47) @jeromelecoq, where else can we look?

**Comment by jeromelecoq** [comment]
We will try Visual Behavior NWB for choosing ccf view because of #47

**Comment by rcpeene** [comment]
Currently looking at dandiset 000022 for neuropixel

**Comment by rcpeene** [comment]
Will use visual coding file (dandiset 00021) for the LFP visualization

**Comment by rcpeene** [comment]
I looked at every dandiset with neuropixel data and none of them have valid CCF coordinates in the 'probes' tab.

**Comment by jeromelecoq** [comment]
Given that all NWB neuropixel datasets on dandy, except for illusion, have incomplete or absent CCF data. We will use the visual coding as an example here.

**Comment by jeromelecoq** [comment]
This was addressed
