### ISSUE TITLE
Update nwbwidget version

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#68]
nwbwidgets implemented a fix which allows us to visualize ROIs in ophys files. To use this, I must update the version of nwbwidgets.

**Comment by rcpeene** [comment]
Waiting on a new nwbwidgets release for these changes to take effect.

**Comment by jeromelecoq** [comment]
Release typically at the end of months?

**Comment by jeromelecoq** [comment]
We have an alternate way to display ROI and this is submitted to them. 
So we don't need to track this here. 
Plan is to update our package once it is deployed
