### ISSUE TITLE
Include depth in LFP axis

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#71]
As per a change discussed in issue #19, we want to include the depth in the stack display of LFP traces. As of right now, I don't know of any way to extract the actual depth of a probe unit. All I'm aware of that I have access to in the NWB file is the CCF information and the probe unit number.

**Comment by rcpeene** [comment]
At the moment, I am just going to plot the depth assuming probe unit 0 is at depth 0 and that they are 20 mm apart. This is imperfect.

**Comment by rcpeene** [comment]
There may be no easy way to do this. As of now, I don't know of any depth information recorded within the NWB files besides the CCF coordinates, and translating CCF coords to actual depth isn't easy since I don't know how deep each probe is inserted. We'll discuss options.

**Comment by jeromelecoq** [comment]
Just use the probe number for now.

**Comment by rcpeene** [comment]
Jerome indicated he'd like the depth plot to use color to indicate depth rather than just axis labels.

**Comment by rcpeene** [comment]
I have colored the depth plot and remove axis labels, since there's no robust way to represent depth.

**Comment by jeromelecoq** [comment]
We reviewed the depth plot with regards to confidence interval and there was a bug related to the loop. the CI was added at each iteration on top of each other making the interval only correct for the first plot.

**Comment by rcpeene** [comment]
I added a colorbar which is labeled with the channel number.
