### ISSUE TITLE
Develop an eye tracking visualization notebook

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#73]
Here is an example notebook with views
https://alleninstitute.github.io/AllenSDK/_static/examples/nb/brain_observatory.html

**Comment by jeromelecoq** [comment]
@rcpeene will also look at the Slack thread on eye tracking in the illusion project

**Comment by jeromelecoq** [comment]
@rcpeene started working on this. He is confused with the Datatype of the underlying object associated with eye tracking. 
This should be helpful: https://visual-behavior-ophys-data.s3.us-west-2.amazonaws.com/visual-behavior-ophys/VBP_WhitePaper_SDK_Documentation.pdf

**Comment by jeromelecoq** [comment]
@rcpeene investigating data types and consolidating between the SDK, and the pdf

**Comment by rcpeene** [comment]
PR here #90

**Comment by jeromelecoq** [comment]
After modifying the notebook to do streaming, it worked well. 

I recommend we ask Adam about the .data value in eye_tracking. It is not entirely clear what is being plotted. 
Whether it is screen-coords, or pupil coordinates in the eye tracking camera or else.

**Comment by rcpeene** [comment]
We talked to Adam. The units of the x and y coordinates are pixels on the mouse eye-camera, where 0 is top left. I should add units to the notebook and alter the markdown to explain this.

**Comment by rcpeene** [comment]
PR has been merged.
