### ISSUE TITLE
Figure out how to clear fsspec cache

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#76]
When streaming large files, the nwb cache fills up very rapidly, and doesn't get cleared between sessions. This is annoying and requires manually deleting the cache. I bet there's a way to have fsspec automatically clear this.

**Comment by jeromelecoq** [comment]
They provided a simple fix to @rcpeene this morning

**Comment by rcpeene** [comment]
Have implemented this fix.
