### ISSUE TITLE
Fix CI bug in LFP notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#77]
Jerome mentioned this here #71. Basically, the confidence intervals displayed on the plot are incorrect; each new trace it displayed had an increasingly large interval.

**Comment by rcpeene** [comment]
Removing the `+/- CI` line from the code doesn't change this trend of increasingly large confidence interval. After playing around with the code, examining the average of the CI at different depths, and looking at a different set of channels, it looks like this is not a bug but a property of the data.

**Comment by jeromelecoq** [comment]
I think you are right after looking at this in more depth. 

I did find a mistake in the CI code 
This

n = windows.shape[1]

should be 

n = windows.shape[0]

the n is along the repeat number not the time dimension.

**Comment by rcpeene** [comment]
This has been fixed.
