### ISSUE TITLE
Explore hosting options other than mybinder.org

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#81]
mybinder.org has some memory and OS limitations that have become obstacles to our usage. There might be alternatives.

**Comment by rcpeene** [comment]
So far we have not encountered any more significant problems. We may revisit this in the future but unlikely to be soon.

**Comment by jeromelecoq** [comment]
For now, we will close, We might have to make a dummy dataset to avoid this issue. 
Keeping our notebook small does help dissemination.
