### ISSUE TITLE
Optimize LFP notebook so interpolation consumes less memory

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#82]
@jeromelecoq discovered that running the `visualize_lfp` notebook crashes when running on binder. This is because the LFP interpolation step consumes a significant amount of memory. I will have to design a way so that only a period of the LFP and stimulus data are used in interpolation so that it consumes less memory.

**Comment by rcpeene** [comment]
Just made this commit 9df5f9f6738b909acaa0ee70380b2db9680d5794 to address this problem. Now users can select a period of time within the LFP data to analyze if interpolating all of the data consumes too much memory.

**Comment by jeromelecoq** [comment]
@rcpeene will launch in binder

**Comment by rcpeene** [comment]
Pushed a fix which allows for usage within Binder's 2GB.

**Comment by jeromelecoq** [comment]
As far as I can tell. The notebook on the branch does not work directly on binder. The path is still set to a local windows path.

**Comment by rcpeene** [comment]
This was a problem of the period selection; it was slightly too large. I made it smaller. This worked for me on binder.
