### ISSUE TITLE
Test notebooks with github actions

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#84]
We need a robust way to simply run Jupyter notebooks -- checking if they run without fail -- in a github action. I bet this already exists somewhere. I will have to explore.

**Comment by rcpeene** [comment]
I've amended the build workflow to use nbmake to test Jupyter notebooks for pushes to main and dev. It's worth noting that these checks take a long time -- between downloading nwb files in almost every notebook and running some computationally-heavy operations -- it will probably take dozens of minutes in the future to test all notebooks.

**Comment by rcpeene** [comment]
Will close this issue when other PRs are merged and I can confirm this fully works.

**Comment by jeromelecoq** [comment]
We discussed how to handle embargod dataset and decided to use an env variable for now.

**Comment by rcpeene** [comment]
We have our first passing build test on dev. This works!
