### ISSUE TITLE
Alter neuropixel display script to use ccfwidgets

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#87]
After the problems discussed in issue #42, we've resolved to try and replace the brainrender dependency with [ccf widget](https://github.com/NeurodataWithoutBorders/ccf-widget). This will probably run faster and not crash on binder.

**Comment by rcpeene** [comment]
I've made these changes and it functions well. There seems to be some broken functionality in ccf widgets with coloring the probe markers. I've made a ticket for for adding functionality #91.

**Comment by rcpeene** [comment]
This works well except there it does not work on binder. When running the final cell to display the widget I get `Error displaying widget: model not found`. I believe this is the result of some mismatched dependencies. I will investigate more.

**Comment by rcpeene** [comment]
I believe this to be an upstream problem with ipympl. I've commented on some existing issues there.

**Comment by jeromelecoq** [comment]
@rcpeene to write at the top of the notebook in BOLD if there are incompatibilities with binder

**Comment by jeromelecoq** [comment]
@rcpeene looking into whether there is a dependency issue. Some maintainers of the package provided some guidance. Will copy message here

**Comment by jeromelecoq** [comment]
@rcpeene will add text to point at running this outside of Binder and close

**Comment by rcpeene** [comment]
Still working with ipympl on github to figure out a solution. In the meantime, I will add a disclaimer in the relevant notebooks saying it does not work on binder.

**Comment by rcpeene** [comment]
Disclaimer has been added and pushed to branch `neuropixel_probes`. PR will be issued.

**Comment by jeromelecoq** [comment]
@rcpeene will ping the team on the issue. If they address it in the days or so, we will incorporate their change otherwise, we should find an alternative way

**Comment by jeromelecoq** [comment]
A potential solution is to upgrade JupyterHub within binder deployed docker.

**Comment by rcpeene** [comment]
Filed an issue with ipympl: https://github.com/matplotlib/ipympl/issues/511

**Comment by rcpeene** [comment]
While this is still probably good to solve, issue #148 serves as a workaround.

**Comment by rcpeene** [comment]
Closing this. Will make a new ticket if ccf-widgets ever makes bugfix
