### ISSUE TITLE
Resolve different filepaths with Thebe

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#93]
Related discussion in issue #79. We need to figure out a way to ensure filepaths in Thebe work with the same filepaths as binder. The problem is that the default working directory in thebe is the home directory and in binder its the directory of the notebook. The solution is mentioned [here](https://github.com/executablebooks/jupyter-book/issues/1304). I will need to implement something similar.

**Comment by jeromelecoq** [comment]
We discussed using "./" instead which should work on every platforms.

**Comment by rcpeene** [comment]
Jerome's idea is much simpler and more elegant. We will go with this.
